### ISSUE TITLE
Lowercase 't' looks out of place

### ISSUE THREAD

**Issue by aschultz** [coreywho/Urbanist#16]
The images in the README show lowercase 't' with a crossbar lined up with x-height, which looks very nice, but the current font files render 't' with a much lower crossbar that appears out of place next to most other characters (particularly 'r' and 'z'). 'f' shares the same crossbar height, but is less awkward looking due to its taller ascender.

**Comment by coreywho** [comment]
Thanks for opening the issue! I agree it looks off. I created PR #17 to align both 't' and 'f' crossbars to match the x-height. There's a pre-release of the exported font files on the release page if you want to check them out!
